### ISSUE TITLE
Story: Confirm Box

### ISSUE THREAD

**Issue by luciademoja** [CraftAcademy/rails-messaging-june#24]
Feature: Confirm Box 
As a user,
when I click on ok in the confirm box
I would like my conversation to be moved to trash
And if I click cancel
I would like to return to my conversation.

**Comment by luciademoja** [comment]
Not sure if we can wrap the if statement that covers this function in only one feature. But we would really like to do it.

**Comment by rdcsg** [comment]
Is this story about how to put stuff into trash? Isn't it missing the first step of actually deleting the message?

**Comment by rdcsg** [comment]
Redundant story already part of story #20.
